# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purchDate', models.DateTimeField(verbose_name='Date Purchased')),
                ('price', models.FloatField(default=0.0)),
                ('numSold', models.IntegerField(default=0, verbose_name='Number Sold')),
                ('lastPrice', models.FloatField(default=0.0)),
                ('priceChange', models.FloatField(default=0.0)),
                ('icon', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time of Sale')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0.0)),
                ('beerSold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Beer')),
            ],
        ),
    ]
