# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_beer_lastprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='ABV',
            field=models.FloatField(default=4.2),
        ),
    ]
